### ISSUE TITLE
submission instruction

### ISSUE THREAD

**Issue by jianructose** [UBC-MDS/majacloud#31]
SUBMISSION: Please put a link in canvas where TAs can find the following-

- [x] Python 3 notebook, with the code for ML model in scikit-learn. (You can develop this on your existing jupyterHub in your EC2 instance, from milestone2)

- [x] PySpark notebook, with the code for obtaining best hyperparameter settings. ( For this you have to use PySpark notebook in your EMR cluster )

- [x] Screenshot from 
    - [x] Setup your EMR cluster (Task 1).
    - [x] Setup your browser , jupyter environment & connect to the master node (Task 2). 
    - [x] Your S3 bucket showing model.joblib file. (From Task 3 Develop a ML model using scikit-learn)

**Comment by shoebillm** [comment]
Python 3 notebook, with the code for ML model in scikit-learn. (You can develop this on your existing jupyterHub in your EC2 instance, from milestone2)
https://github.com/UBC-MDS/majacloud/blob/main/notebooks/milestone3/Milestone3-Task3.ipynb
[ ] PySpark notebook, with the code for obtaining best hyperparameter settings. ( For this you have to use PySpark notebook in your EMR cluster )
https://github.com/UBC-MDS/majacloud/blob/main/notebooks/milestone3/Milestone3-Task4.ipynb
[ ] Setup notebook
https://github.com/UBC-MDS/majacloud/blob/main/notebooks/milestone3/Milestone3.ipynb

[ ] Screenshot from
[ ] Setup your EMR cluster (Task 1).
https://github.com/UBC-MDS/majacloud/blob/main/images/m3_1.png
[ ] Setup your browser , jupyter environment & connect to the master node (Task 2).
https://github.com/UBC-MDS/majacloud/blob/main/images/m3-2.png

[ ] Your S3 bucket showing model.joblib file. (From Task 3 Develop a ML model using scikit-learn)
https://github.com/UBC-MDS/majacloud/blob/main/images/m3-3.png
